In [1]:
import pandas as pd
import numpy as np

In [10]:
df_plan = pd.read_csv('тест_бюджет.csv').replace(';', ',')


df_fact = pd.read_csv('data.csv')

In [12]:
df_plan

                                                                      object;object_type; planned_expense ;planned_revenue
СКВ.1496Л-56 Поточное [дог.17С1490] [ЗБП];Забой... 00 ₽ ;13 000 000                                                 0.0
СКВ.1891Л-299 Тевлинско-Русскинское [дог.17С149... 00 ₽ ;2 470 000                                                  0.0
СКВ.2057Н-44Б Повховское [дог.17С1490] [ЗБП];За... 00 ₽ ;4 290 000                                                  0.0
СКВ.227-23 Повховское [дог.17С1490] [ЗБП];Забой... 00 ₽ ;5 200 000                                                  0.0
СКВ.10442Р Шушминское [дог.19С1114] [ББ];Бурени... 00 ₽ ;29 900 000                                                 0.0
СКВ.12301Г-123 им. А.Усольцева (бывш Имилорское... 00 ₽ ;45 500 000                                                 0.0
СКВ.12304Г-123 им. А.Усольцева (бывш Имилорское... 00 ₽ ;35 100 000                                                 0.0
СКВ.12305Г-123 им. А.Усольцева (бывш Имилорское... 00 ₽ ;84 500 000                                                 0.0
СКВ.1702Г-4 Мишаевское [дог.19С1115] [ББ];Бурен... 00 ₽ ;104 000 000                                                0.0
СКВ.2020Г-7 Малоключевое [дог.19С1115] [ББ];Бур... 00 ₽ ;65 000 000                                                 0.0
СКВ.31В-795 Нивагальское [дог.19С1115] [ББ];Бур... 00 ₽ ;35 100 000                                                 0.0
СКВ.4401Г-440 Покачевское [дог.19С1115] [ББ];Бу... 00 ₽ ;7 670 000                                                  0.0
;;;                                                nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN
                                                   nan                                                              NaN

In [9]:
df_fact

,contractor,contract_num,date,object_name,expenses,revenue,profit
0,Лукойл,17С1490,07.08.2017,СКВ.1496Л-56 Поточное [дог.17С1490] [ЗБП],0.00,4397874.91,4397874.91
1,Лукойл,17С1490,07.08.2018,СКВ.1891Л-299 Тевлинско-Русскинское [дог.17С14...,1835273.99,2063962.72,228688.73
2,Лукойл,17С1490,07.08.2019,СКВ.2057Н-44Б Повховское [дог.17С1490] [ЗБП],2249093.08,3526455.98,1277362.90
3,Лукойл,17С1490,07.08.2020,СКВ.227-23 Повховское [дог.17С1490] [ЗБП],2694737.75,4776891.76,2082154.01
4,Лукойл,17С1490,07.08.2023,СКВ.10442Р Шушминское [дог.19С1114] [ББ],36700045.94,30427743.06,-6272302.88
5,Лукойл,17С1490,07.08.2024,СКВ.12301Г-123 им. А.Усольцева (бывш Имилорско...,8800.00,0.00,-8800.00
6,Лукойл,17С1490,07.08.2025,СКВ.12304Г-123 им. А.Усольцева (бывш Имилорско...,28352.48,0.00,-28352.48
7,Лукойл,17С1490,07.08.2026,СКВ.12305Г-123 им. А.Усольцева (бывш Имилорско...,40156292.43,72764387.91,32608095.48
8,Лукойл,17С1490,07.08.2029,СКВ.1702Г-4 Мишаевское [дог.19С1115] [ББ],4998.46,0.00,-4998.46